---
title: "wage_theft_guest_workers"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Suppress scientific notation
options(scipen = 999)
```

```{r install packages, include = FALSE}
install.packages(c("formattable", "ggplot2", "ipumsr", "janitor", "lubridate", "psych", "tidyverse"))
```

```{r load packages, include = FALSE}
library(formattable)
library(ggplot2)
library(ipumsr)
library(janitor)
library(lubridate)
library(psych)
library(readxl)
library(tidyverse)
```

```{r import data, include = FALSE}
# CASE_ACT_EER_SUM

col_names_case_act_eer_sum <- c("CASE_ID", "ACT_ID", "CASE_EER_ID", "ER_EE_VIOL", "TTL_ACT_VIOLATIONS", "AMT_BW_COMPUTED", "AMT_BW_ASSESSED", "AMT_LD_ASSESSED", "TTL_BW_PAID", "TTL_CMP_PAID", "RESOLUTION_DATE", "RESOLUTION_EE_CNT", "RESOLUTION_BW_AMT", "RESOLUTION_CMP_AMT", "DATE_BW_PAID", "DATE_CMP_PAID", "FLAG_INCLUDE", "DATE_CHANGED")

case_act_eer_sum <- read_delim("data/case_act_eer_sum.txt",
                               "|",
                               col_names = col_names_case_act_eer_sum)

# CASE_ACT_EER_VIOL

col_names_case_act_eer_viol <- c("CASE_ID", "ACT_ID", "CASE_EER_ID", "VIOLATION_ID", "HAZ_OCCP_ID", "ACT_SPECIFIC_INFO", "ER_EE_VIOL", "VIOLATION_TYPE", "DATE_BEG_VIOL", "DATE_END_VIOL", "CMP_AMT_AT_INVEST", "AMT_BW_COMPUTED", "AMT_BW_ASSESSED", "AMT_LD_ASSESSED", "EE_AGE_AT_VIOL", "INJURY_VIOLATION", "INJURY_LEVEL_ID", "DATE_OF_INJURY", "AGE_AT_INJURY", "ACCIDENT_REPORT", "TIME_LOST_ON_JOB", "NUM_EES_REPRESENTD", "OTHER_EES_INVOLVED", "OTH_COMPLY_ACTIONS", "COMPLIANCE_STATUS", "COMPLY_REASON_ID", "VIOL_OCCURANCE", "CORRECTED_VIOL", "OSHA_COMBINED", "REASON_ID")

case_act_eer_viol <- read_delim("data/case_act_eer_viol (1).txt",
                                "|",
                                col_names = col_names_case_act_eer_viol)

# CASE_ACT_SUMMARY

col_names_case_act_summary <- c("CASE_ID", "ACT_ID", "TTL_ACT_VIOLATIONS", "DATE_FINDINGS_SUB", "FINDINGS_TOTAL_EES", "FINDINGS_EE_CNT", "AGRD_TO_DATE", "AGRD_TO_EES_CNT", "AMT_BW_COMPUTED", "AMT_BW_ASSESSED", "AMT_BW_PD_TO_DATE", "AMT_LD_ASSESSED", "AMT_CMP_PD_TO_DATE", "DATE_RESOLUTION", "RESOLUTION_EE_CNT", "RESOLUTION_BW_AMT", "RESOLUTION_CMP_AMT", "RESOLVE_REASON_ID", "COMPLIANCE_ID", "PAID_TO_DATE", "PAID_EES_CNT", "DATE_SYS_UPDATE", "FLAG_DETAIL_SUM")

case_act_summary <- read_delim("data/case_act_summary (1).txt",
                               "|",
                               col_names = col_names_case_act_summary)

# ACTS
col_names_acts <- c("ACT_ID", "ACT_NAME", "ACT_GROUP", "ACT_CONCIL_ABILITY", "ACT_WORKFORCE_MIN", "ACT_WORKFORCE_MAX", "ACT_MIN_REVENUE", "SORT_ORDER", "ACTIVE_FLAG", "CMP_EXCEPT_PERIOD")

acts <- read_delim("data/v_act (1).txt",
                   "|",
                   col_names = col_names_acts)
# ACT_VIOLATIONS

col_names_act_violations <- c("VIOLATION_ID", "ACT_ID", "VIOLATION_NO", "VIOLATION_TYPE", "VIOLATION_DESC", "EE_ER_VIOL", "START_AGE", "END_AGE", "FLAG_COMPUTE_FB", "ACTIVE_FLAG")

act_violations <- read_delim("data/v_act_violations.txt",
                             "|",
                             col_names = col_names_act_violations)

# KASE

col_names_kase <- c("CASE_ID", "CASE_STATUS_ID", "COMPLIANCE_ID", "INVESTIGATING_RO", "INVESTIGATING_DO", "INVESTIGATING_AO", "INVESTIGATING_FO", "DATE_BEG_INV_PER", "DATE_END_INV_PER", "DATE_CONCLUDED", "CONCLUDE_REASON_ID", "UNDUP_EES_COMPUTED", "UNDUP_EES_ASSESSED", "UNDUP_EES_VIOLATED", "TTL_CASE_VIOLATION", "AMT_BW_COMPUTED", "AMT_BW_ASSESSED", "TTL_BW_PD_TO_DATE", "TTL_CMP_PD_TO_DATE", "AMT_LD_ASSESSED", "AMT_BW_RESOLVED", "AMT_CMP_RESOLVED", "DATE_REGISTERED", "INVEST_TOOL_ID", "RECURR_VIOL", "REINVESTIGATION", "REPEAT_VIOLATION", "REGISTRATION_ACT")

kase <- read_delim("data/kase (1).txt",
                   "|",
                   col_names = col_names_kase)

# CASE_STATUS

col_names_case_status <- c("CASE_STATUS_ID", "CASE_STATUS_DESC", "SORT_ORDER", "ACTIVE_FLAG", "PICKLIST_DEF")

case_status <- read_delim("data/v_case_status.txt",
                          "|",
                          col_names = col_names_case_status)

# CONCLUDED_REASON

col_names_concluded_reason <- c("REASON_ID", "REASON_DESC", "ACTIVE_FLAG")

concluded_reason <- read_delim("data/v_concluded_reason.txt",
                               "|",
                               col_names = col_names_concluded_reason)

# CASE_EMPLOYER

col_names_case_employer <- c("CASE_ID", "ER_TRADE_NAME", "ER_TRADE_SOUNDEX", "ER_LEGAL_NAME", "ER_LEGAL_SOUNDEX", "ER_ADDR1", "ER_ADDR2", "ER_ADDR3", "ER_CITY", "ER_STATE_ID", "ER_ZIP", "ER_PHONE1", "ER_PHONE2", "ER_FAX", "ER_FAX_EXT", "ER_EIN", "ER_COUNTY_ID", "ER_TYPE_ID", "ER_BUS_ORG", "ER_NAICS", "ER_SIC_CODE", "ER_NATURE_OF_BUS", "ER_IC_COVERAGE_ID", "ER_NUM_OF_EES", "ER_NUM_EE_AFFECTED", "ER_NUM_BRANCHES", "ER_BR_OUTSIDE_AO", "ER_BNPI", "PENALTY_TYPE", "EST_TYPE_ID", "EST_STATUS_ID", "EST_CERT_TYPE", "SPEC_COVERAGE_ID", "WORKSHOP_TYPE", "TTL_EES_CURRENT_YR", "TTL_EES_PRECEDE_YR", "ST_LOCAL_GOVT", "ER_PERM_ADDR1", "ER_PERM_ADDR2", "ER_PERM_ADDR3", "ER_PERM_CITY", "ER_PERM_STATE_ID", "ER_PERM_ZIP", "ER_PERM_PHONE1", "ER_PERM_PHONE2", "ER_PERM_INTNTL_PH", "ER_PERM_FAX", "ER_PERM_FAX_EXT", "ER_PERM_COUNTY_ID", "LENG_LOCAL_STAY", "ER_AGENCY_TYPE", "ENDING_DAY_OF_WEEK", "DATE_BUS_OPENED")

case_employer <- read_delim("data/case_employer (3.25.21).txt",
                            "|",
                            col_names = col_names_case_employer)

# BUS_ORG_TYPE

col_names_bus_org_type <- c("BUS_TYPE_ID", "BUS_TYPE_DESC", "SORT_ORDER", "ACTIVE_FLAG", "PICKLIST_DEF")

bus_org_type <- read_delim("data/v_bus_org_type.txt",
                           "|",
                           col_names = col_names_bus_org_type)

# NAICS

col_names_naics <- c("NAICS", "NAICSTEXT")

naics <- read_delim("data/v_naics.txt",
                    "|",
                    col_names = col_names_naics)

# Employment by industry

employment_by_industry <- read_csv("data/employment_by_industry.csv",
                                             col_types = cols(.default = "?",
                                                              ER_NAICS_THREE_DIGITS = "c"))

# (Nonimmigrant visa statistics)[https://travel.state.gov/content/travel/en/legal/visa-law0/visa-statistics/nonimmigrant-visa-statistics.html]
path <- "data/visas_by_type_and_year.xlsx"

visas <- path %>% 
  # Get sheet names
  excel_sheets() %>% 
  set_names() %>% 
  # Combine all sheets
  map_df(read_excel,
      path = path,
      .id = "FISCAL_YEAR") %>% 
  select("FISCAL_YEAR", "H-2A", "H-2B") %>% 
  # Filter out fiscal years prior to 2006
  filter(str_detect(FISCAL_YEAR, regex("FY9|00|01|02|03|04|05"), negate = T)) %>% 
  clean_names(case = "all_caps")
```

```{r prepare data, include = FALSE}
# Return guest worker-related cases.
guest_worker_case_ids <- kase %>% 
  filter(REGISTRATION_ACT %in% c("H2A", "H2B")) %>% 
  pull(CASE_ID)

# Return the data for those cases in the kase and case_employer tables.
guest_worker_cases <- kase %>% 
  inner_join(case_employer,
             by = "CASE_ID") %>% 
  # Filter to only the guest worker MW or OT cases identified above
  filter(CASE_ID %in% guest_worker_case_ids) %>% 
  # Replace NA values with zeros, convert dates and calculate the length of cases
  mutate(across(16:20, ~replace_na(., 0)),
         DATE_REGISTERED = as.Date(parse_date_time(DATE_REGISTERED, "Ymd")),
         DATE_CONCLUDED = as.Date(parse_date_time(DATE_CONCLUDED, "Ymd")),
         CASE_LENGTH = DATE_CONCLUDED - DATE_REGISTERED) %>% 
  # Remove junk case lengths
  filter(!is.na(CASE_LENGTH),
         CASE_LENGTH > 0) %>% 
  select(1, 43, 29, 36:38, 44, 47, 28, 11, 23, 10, 14, 17:20)
  
# Create a function to return the most common values in the state and NAICS columns
Modes <- function(x) {
  ux <- unique(x)
  tab <- tabulate(match(x, ux))
  ux[tab == max(tab)]
}

# Create table of employer aggregates.
guest_worker_employers <- guest_worker_cases %>% 
  # Filter out junk EINs so we can accurately group
  filter(!is.na(ER_EIN),
         !(ER_EIN %in% c("(b)(7)(E)", "NA", "ER Refused", "EIN Missing", "Dropped", "Owner SSN",
                         "00-0000000", "99-9999999", "Conciliate", "Conciliated"))) %>% 
  group_by(ER_EIN) %>% 
  summarize(TRADE_NAMES = paste0(ER_TRADE_NAME, collapse = ", "),
            MOST_COMMON_CITY = paste0(Modes(ER_CITY), collapse = ', '),
            MOST_COMMON_STATE = paste0(Modes(ER_STATE_ID), collapse =', '),
            NAICS = paste0(Modes(ER_NAICS), collapse =', '),
            NUM_CASES = n(),
            CASE_IDS = paste0(CASE_ID, collapse = ", "),
            REGISTRATION_ACTS = paste0(REGISTRATION_ACT, collapse = ", "),
            CONCLUDE_REASONS = paste0(CONCLUDE_REASON_ID, collapse = ", "),
            TTL_EMP_AMT_BW_ASSESSED = sum(AMT_BW_ASSESSED, na.rm = TRUE),
            TTL_EMP_AMT_BW_PD_TO_DATE = sum(TTL_BW_PD_TO_DATE, na.rm = TRUE),
            TTL_EMP_CMP_PD_TO_DATE = sum(TTL_CMP_PD_TO_DATE, na.rm = TRUE),
            TTL_EMP_AMT_LD_ASSESSED = sum(AMT_LD_ASSESSED, na.rm = TRUE),
            TTL_UNDUP_EES_VIOLATED = sum(UNDUP_EES_VIOLATED)) %>% 
  select(ER_EIN,
         TRADE_NAMES,
         MOST_COMMON_CITY,
         MOST_COMMON_STATE,
         NAICS,
         NUM_CASES,
         CASE_IDS,
         REGISTRATION_ACTS,
         CONCLUDE_REASONS,
         TTL_EMP_AMT_BW_ASSESSED,
         TTL_EMP_AMT_BW_PD_TO_DATE,
         TTL_EMP_CMP_PD_TO_DATE,
         TTL_EMP_AMT_LD_ASSESSED,
         TTL_UNDUP_EES_VIOLATED)

# Create table of industry aggregates.
guest_worker_industries <- guest_worker_cases %>% 
  # Create a three-digit NAICS column
  mutate(ER_NAICS_THREE_DIGITS = substr(ER_NAICS, 1, 3)) %>% 
  group_by(ER_NAICS_THREE_DIGITS) %>% 
  summarize(NUM_CASES = n(),
            TTL_EMP_AMT_BW_ASSESSED = sum(AMT_BW_ASSESSED, na.rm = TRUE),
            TTL_EMP_AMT_BW_PD_TO_DATE = sum(TTL_BW_PD_TO_DATE, na.rm = TRUE),
            TTL_EMP_CMP_PD_TO_DATE = sum(TTL_CMP_PD_TO_DATE, na.rm = TRUE),
            TTL_EMP_AMT_LD_ASSESSED = sum(AMT_LD_ASSESSED, na.rm = TRUE),
            TTL_UNDUP_EES_VIOLATED = sum(UNDUP_EES_VIOLATED)) %>% 
    select(ER_NAICS_THREE_DIGITS,
         NUM_CASES,
         TTL_EMP_AMT_BW_ASSESSED,
         TTL_EMP_AMT_BW_PD_TO_DATE,
         TTL_EMP_CMP_PD_TO_DATE,
         TTL_EMP_AMT_LD_ASSESSED,
         TTL_UNDUP_EES_VIOLATED) %>% 
  left_join(employment_by_industry, by = "ER_NAICS_THREE_DIGITS") %>% 
  mutate(CASES_PER_HUNDRED_THOUSAND_EMPLOYED = round(NUM_CASES / TOTAL_INDUSTRY_EMPLOYMENT * 100000, digits = 1)) %>% 
  select(1, 8:11, 2:7)

guest_worker_industries %>% 
  View()

# Export guest workers by industry
guest_worker_industries %>% 
  write_csv("data/exported/guest_workers/guest_worker_industries.csv")

# Create table of visa issuances by fiscal year
visas_by_year <- visas %>% 
  group_by(FISCAL_YEAR) %>% 
  summarize(VISAS_H2A = max(H_2A, na.rm = T),
            VISAS_H2B = max(H_2B, na.rm = T)) %>% 
  mutate(FISCAL_YEAR = as.numeric(str_replace(FISCAL_YEAR, "FY", "20")))
```

```{r top-line numbers, include=FALSE}
# How many guest worker-related cases and affected employees have there been? And how much in back wages, civil monetary penalties and liquidated damages were paid out in these cases?
guest_worker_cases %>% 
  summarize(num_cases = n(),
            sum_undup_ees_violated = sum(UNDUP_EES_VIOLATED),
            sum_amt_bw_assessed = sum(AMT_BW_ASSESSED),
            sum_ttl_cmp_pd_to_date = sum(TTL_CMP_PD_TO_DATE),
            sum_amt_ld_assessed = sum(AMT_LD_ASSESSED))
```

```{r How are these cases broken up?, include = FALSE}
guest_worker_cases %>% 
  group_by(REGISTRATION_ACT) %>% 
  summarize(NUM_CASES = n()) %>% 
  mutate(PCT_CASES = round(NUM_CASES / sum(NUM_CASES) * 100, 0)) %>% 
  select(REGISTRATION_ACT, NUM_CASES, PCT_CASES) %>% 
  arrange(desc(NUM_CASES))
```

```{r cases vs. visas, include = FALSE}
guest_worker_cases_by_year <- guest_worker_cases %>% 
  # Extract the fiscal year from case registration date
  group_by(REGISTRATION_ACT, FISCAL_YEAR = as.numeric(str_sub(quarter(DATE_REGISTERED, with_year = TRUE, fiscal_start = 10), 1, 4))) %>% 
  summarize(NUM_CASES = n()) %>% 
  select(FISCAL_YEAR, REGISTRATION_ACT, NUM_CASES) %>% 
  # Pivot the data frame wider
  pivot_wider(names_from = REGISTRATION_ACT, values_from = NUM_CASES, values_fill = 0, names_prefix = "CASES_") %>% 
  # Join with the visa issuances data frame
  inner_join(visas_by_year, by = "FISCAL_YEAR") %>% 
  mutate(CASES_TOTAL =  CASES_H2A + CASES_H2B,
         VISAS_TOTAL = VISAS_H2A + VISAS_H2B,
         CASES_PCT_CHANGE = round(CASES_TOTAL / lag(CASES_TOTAL) - 1, digits = 2),
         VISAS_PCT_CHANGE = round(VISAS_TOTAL / lag(VISAS_TOTAL) - 1, digits = 2)) %>% 
  select(1:3, 6, 4, 5, 7, 8, 9)

# Export cases by year
guest_worker_cases_by_year %>% 
  write_csv("data/exported/guest_workers/guest_worker_cases_by_year.csv")

guest_worker_cases_by_year
```

```{r When did H-2B cases start getting reported?, include = FALSE}
guest_worker_cases %>% 
  filter(REGISTRATION_ACT == "H2B") %>% 
  select(CASE_ID, REGISTRATION_ACT, DATE_REGISTERED) %>% 
  arrange(DATE_REGISTERED)
```

```{r Plot total cases and visa issuances by year., include = FALSE}
plot_guest_worker_cases_visas_by_year <- guest_worker_cases %>% 
  # Extract the fiscal year from case registration date
  group_by(FISCAL_YEAR = as.numeric(str_sub(quarter(DATE_REGISTERED, with_year = TRUE, fiscal_start = 10), 1, 4))) %>% 
  summarize(NUM_CASES = n()) %>% 
  select(FISCAL_YEAR, NUM_CASES) %>% 
  # Join with the visa issuances data frame
  inner_join(visas_by_year, by = "FISCAL_YEAR") %>% 
  mutate(NUM_VISAS = VISAS_H2A + VISAS_H2B) %>% 
  select(FISCAL_YEAR, NUM_CASES, NUM_VISAS) %>% 
  # Remove FY 2006-2009 and 2020 data
  filter(FISCAL_YEAR > 2009 & FISCAL_YEAR != 2020) %>% 
  ggplot(aes(x = FISCAL_YEAR)) + 
  geom_bar(aes(y = NUM_VISAS), stat = "identity", fill = "tan1", colour = "sienna3") + 
  geom_line(aes(y = NUM_CASES * 500), stat = "identity") + 
  scale_y_continuous(sec.axis = sec_axis(~. / 500, name = "NUM_CASES")) + 
  ggtitle("Wage Theft Cases and Visa Issuances\nFY10 - FY19") + 
  xlim(2010, 2020)

plot_guest_worker_cases_visas_by_year <- guest_worker_cases %>% 
  # Extract the fiscal year from case registration date
  group_by(FISCAL_YEAR = as.numeric(str_sub(quarter(DATE_REGISTERED, with_year = TRUE, fiscal_start = 10), 1, 4))) %>% 
  summarize(NUM_CASES = n()) %>% 
  select(FISCAL_YEAR, NUM_CASES) %>% 
  # Join with the visa issuances data frame
  inner_join(visas_by_year, by = "FISCAL_YEAR") %>% 
  mutate(NUM_VISAS = VISAS_H2A + VISAS_H2B) %>% 
  select(FISCAL_YEAR, NUM_CASES, NUM_VISAS) %>% 
  # Remove FY 2006-2009 and 2020 data
  filter(FISCAL_YEAR > 2009 & FISCAL_YEAR != 2020) %>% 
  ggplot(aes(x = FISCAL_YEAR)) + 
  geom_bar(aes(y = NUM_VISAS), stat = "identity", fill = "tan1", colour = "sienna3") + 
  ggtitle("Visa Issuances\nFY10 - FY19") + 
  xlim(2010, 2020)

print(plot_guest_worker_cases_visas_by_year)
```

```{r Plot total cases and visa issuances by offset year., include = FALSE}
plot_guest_worker_cases_visas_by_offset_year <- guest_worker_cases %>% 
  # Extract the fiscal year from case registration date
  group_by(FISCAL_YEAR = as.numeric(str_sub(quarter(DATE_REGISTERED, with_year = TRUE, fiscal_start = 10), 1, 4))) %>% 
  summarize(NUM_CASES = n()) %>% 
  select(FISCAL_YEAR, NUM_CASES) %>% 
  # Offset the fiscal year
  mutate(FISCAL_YEAR_OFFSET = FISCAL_YEAR - 1) %>% 
  # Join with the visa issuances data frame
  inner_join(visas_by_year, by = c("FISCAL_YEAR_OFFSET" = "FISCAL_YEAR")) %>% 
  mutate(NUM_VISAS = VISAS_H2A + VISAS_H2B) %>% 
  select(FISCAL_YEAR_OFFSET, NUM_CASES, NUM_VISAS) %>% 
 # Remove FY 2006-2009 and 2020 data
  filter(FISCAL_YEAR_OFFSET > 2009 & FISCAL_YEAR_OFFSET != 2020) %>% 
  ggplot(aes(x = FISCAL_YEAR_OFFSET)) + 
  geom_bar(aes(y = NUM_VISAS), stat = "identity", fill = "tan1", colour = "sienna3") + 
  geom_line(aes(y = NUM_CASES * 500), stat = "identity") + 
  scale_y_continuous(sec.axis = sec_axis(~. / 500, name = "NUM_CASES")) + 
  ggtitle("Wage Theft Cases and Visa Issuances Offset\nFY10 - FY19") + 
  xlim(2010, 2020)

print(plot_guest_worker_cases_visas_by_offset_year)
```

```{r Plot the correlation of cases with visas., include = FALSE}
scatter_guest_worker_cases_visas_by_year <- guest_worker_cases %>% 
  # Extract the fiscal year from case registration date
  group_by(FISCAL_YEAR = as.numeric(str_sub(quarter(DATE_REGISTERED, with_year = TRUE, fiscal_start = 10), 1, 4))) %>% 
  summarize(NUM_CASES = n()) %>% 
  select(FISCAL_YEAR, NUM_CASES) %>% 
  # Remove FY 2020 data
  filter(FISCAL_YEAR != 2020) %>% 
  # Join with the visa issuances data frame
  inner_join(visas_by_year, by = "FISCAL_YEAR") %>% 
  mutate(NUM_VISAS = VISAS_H2A + VISAS_H2B) %>% 
  select(FISCAL_YEAR, NUM_CASES, NUM_VISAS) %>% 
ggplot(aes(x = NUM_VISAS, y = NUM_CASES)) + 
  geom_point(size = 3, shape = 1) + 
  geom_smooth(method = "auto", se = FALSE, fullrange = FALSE, level = 0.95)

print(scatter_guest_worker_cases_visas_by_year)
```

```{r Plot cases by registration act by year, include = FALSE}
plot_guest_worker_cases_by_reg_act_year <- guest_worker_cases %>% 
  # Extract the fiscal year from case registration date
  group_by(REGISTRATION_ACT, FISCAL_YEAR = as.numeric(str_sub(quarter(DATE_REGISTERED, with_year = TRUE, fiscal_start = 10), 1, 4))) %>% 
  summarize(NUM_CASES = n()) %>% 
  select(FISCAL_YEAR, REGISTRATION_ACT, NUM_CASES) %>% 
  # Remove FY 2006-2009 and 2020 data
  filter(FISCAL_YEAR > 2009 & FISCAL_YEAR != 2020) %>% 
  ggplot(aes(x = FISCAL_YEAR, y = NUM_CASES, color = REGISTRATION_ACT)) + 
  geom_line() + 
  xlim(2010, 2020) + 
  ggtitle("Wage Theft Cases by\nRegistration Act\nFY10 - FY19")

print(plot_guest_worker_cases_by_reg_act_year)
```

```{r What industries have the highest rate of cases per 100,000 employees?, include = FALSE}
guest_worker_industries %>% 
  arrange(desc(CASES_PER_HUNDRED_THOUSAND_EMPLOYED)) %>% 
  head(5)
```

```{r How have total cases changed by industry and year for the top five industries?, include = FALSE}
top_guest_worker_industry_naics <- guest_worker_industries %>% 
  arrange(desc(CASES_PER_HUNDRED_THOUSAND_EMPLOYED)) %>% 
  head(5) %>% 
  pull(ER_NAICS_THREE_DIGITS)

guest_worker_cases_by_industry_and_year <- guest_worker_cases %>% 
  # Create a three-digit NAICS column
  mutate(ER_NAICS_THREE_DIGITS = substr(ER_NAICS, 1, 3)) %>% 
  filter(ER_NAICS_THREE_DIGITS %in% top_guest_worker_industry_naics) %>% 
  group_by(ER_NAICS_THREE_DIGITS, FISCAL_YEAR = as.numeric(str_sub(quarter(DATE_REGISTERED, with_year = TRUE, fiscal_start = 10), 1, 4))) %>% 
  summarize(NUM_CASES = n()) %>% 
  left_join(employment_by_industry, by = "ER_NAICS_THREE_DIGITS") %>% 
  select(ER_NAICS_THREE_DIGITS,
         DESC_SIMPLIFIED,
         FISCAL_YEAR,
         NUM_CASES) %>% 
  group_by(DESC_SIMPLIFIED) %>% 
  select(DESC_SIMPLIFIED, FISCAL_YEAR, NUM_CASES) %>% 
  # Pivot the data frame wider
  pivot_wider(names_from = DESC_SIMPLIFIED, values_from = NUM_CASES, values_fill = 0, names_prefix = "CASES_") %>% 
  clean_names(case = "all_caps")

# Export cases by industry and year
guest_worker_cases_by_industry_and_year %>% 
  write_csv("data/exported/guest_workers/guest_worker_cases_by_industry_and_year.csv")

guest_worker_cases_by_industry_and_year
```

```{r Plot cases by industry and year, include = FALSE}
plot_guest_worker_cases_by_industry_and_year <- guest_worker_cases %>% 
  # Create a three-digit NAICS column
  mutate(ER_NAICS_THREE_DIGITS = substr(ER_NAICS, 1, 3)) %>% 
  filter(ER_NAICS_THREE_DIGITS %in% top_guest_worker_industry_naics) %>% 
  group_by(ER_NAICS_THREE_DIGITS, FISCAL_YEAR = as.numeric(str_sub(quarter(DATE_REGISTERED, with_year = TRUE, fiscal_start = 10), 1, 4))) %>% 
  summarize(NUM_CASES = n()) %>% 
  # Join with the table of employment by industry data
  left_join(employment_by_industry, by = "ER_NAICS_THREE_DIGITS") %>% 
  select(ER_NAICS_THREE_DIGITS,
         DESC_SIMPLIFIED,
         FISCAL_YEAR,
         NUM_CASES) %>% 
  select(ER_NAICS_THREE_DIGITS, DESC_SIMPLIFIED, FISCAL_YEAR, NUM_CASES) %>% 
  # Remove FY 2020 data
  filter(FISCAL_YEAR != 2020) %>% 
  ggplot(aes(x = FISCAL_YEAR, y = NUM_CASES, color = DESC_SIMPLIFIED)) + 
  geom_line() + 
  xlim(2010, 2020) + 
  ggtitle("Wage Theft Cases by Industry\nFY10 - FY19")

print(plot_guest_worker_cases_by_industry_and_year)
```

```{r Find the Clay Lowry Forestry case, include = FALSE}
guest_worker_cases %>% 
  filter(str_detect(ER_TRADE_NAME, regex("lowry", ignore_case = T)))
```

```{r How long does the average case last for?, include = FALSE}
guest_worker_cases %>% 
  mutate(DATE_REGISTERED = as.Date(parse_date_time(DATE_REGISTERED, "Ymd")),
         DATE_CONCLUDED = as.Date(parse_date_time(DATE_CONCLUDED, "Ymd")),
         CASE_LENGTH = DATE_CONCLUDED - DATE_REGISTERED) %>% 
  summarize(mean(CASE_LENGTH),
            mean(CASE_LENGTH[REGISTRATION_ACT == "H2A"]),
            mean(CASE_LENGTH[REGISTRATION_ACT == "H2B"]))
```

```{r How often are H-2B workers being misclassified?, include = FALSE}
misclassification_violation_ids <- act_violations %>% 
  filter(str_detect(VIOLATION_DESC, regex("improper job classification", ignore_case = TRUE))) %>% 
  pull(VIOLATION_ID)

case_act_eer_viol %>% 
  filter(VIOLATION_ID %in% misclassification_violation_ids) %>% 
  summarize(num_violations = n(),
            sum_ees_represented = sum(NUM_EES_REPRESENTD, na.rm = TRUE),
            sum_amt_bw_assessed = sum(AMT_BW_ASSESSED, na.rm = TRUE),
            sum_amt_ld_assessed = sum(AMT_LD_ASSESSED, na.rm = TRUE))
```

```{r How often are H-2A workers not being provided meals or kitchen facilities?, include= FALSE}
meals_violation_ids <- act_violations %>% 
  filter(ACT_ID == "H2A", str_detect(VIOLATION_DESC, regex("meal", ignore_case = TRUE))) %>% 
  pull(VIOLATION_ID)

case_act_eer_viol %>% 
  filter(VIOLATION_ID %in% meals_violation_ids) %>% 
  summarize(num_violations = n(),
            sum_ees_represented = sum(NUM_EES_REPRESENTD, na.rm = TRUE),
            sum_amt_bw_assessed = sum(AMT_BW_ASSESSED, na.rm = TRUE),
            sum_amt_ld_assessed = sum(AMT_LD_ASSESSED, na.rm = TRUE))
```

```{r How often are H-2A workers not being provided adequate housing?, include = FALSE}
housing_violation_ids <- act_violations %>% 
  filter(ACT_ID == "H2A", str_detect(VIOLATION_DESC, regex("charges for housing|provide housing|housing required but not provided|unlawful deposits", ignore_case = TRUE))) %>% 
  pull(VIOLATION_ID)

case_act_eer_viol %>% 
  filter(VIOLATION_ID %in% housing_violation_ids) %>% 
  summarize(num_violations = n(),
            sum_ees_represented = sum(NUM_EES_REPRESENTD, na.rm = TRUE),
            sum_amt_bw_assessed = sum(AMT_BW_ASSESSED, na.rm = TRUE),
            sum_amt_ld_assessed = sum(AMT_LD_ASSESSED, na.rm = TRUE))
```

```{r How often are H-2A and H-2B workers being forced to pay for recruitment, transportation or visa costs?, include = FALSE}
recruitment_transportation_visa_violation_ids <- c("115", "1523", "1526", "1584", "1585", "1602", "1608", "1609", "1671", "1692", "1757", "1758", "1762", "3021", "3022", "3023", "3025", "3026", "3027", "3136", "3137")

act_violations %>% 
  filter(VIOLATION_ID %in% c("115", "1523", "1526", "1584", "1585", "1602", "1608", "1609", "1671", "1692", "1757", "1758", "1762", "3021", "3022", "3023", "3025", "3026", "3027", "3136", "3137")) %>% 
  View()

case_act_eer_viol %>% 
  filter(VIOLATION_ID %in% recruitment_transportation_visa_violation_ids) %>% 
  summarize(num_violations = n(),
            sum_ees_represented = sum(NUM_EES_REPRESENTD, na.rm = TRUE),
            sum_amt_bw_assessed = sum(AMT_BW_ASSESSED, na.rm = TRUE),
            sum_amt_ld_assessed = sum(AMT_LD_ASSESSED, na.rm = TRUE))
```
